version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./.env
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASS}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
